import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AOS from "aos";

import "aos/dist/aos.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
AOS.init();

export const metadata: Metadata = {
	title: "Global Crypto Hub",
	// description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body
				className={`${inter.className} max-w-[1960px] mx-auto overflow-x-hidden !mr-0`}
			>
				{children}
			</body>
		</html>
	);
}
